"""initial schema

Revision ID: 575836567e28
Revises: 
Create Date: 2026-05-18 11:23:25.838442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '575836567e28'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa_aliada',
    sa.Column('nit', sa.String(length=15), nullable=False),
    sa.Column('nit9', sa.CHAR(length=9), nullable=False),
    sa.Column('nombre_empresa', sa.String(length=200), nullable=False),
    sa.Column('primer_mes', sa.Integer(), nullable=True),
    sa.Column('primer_anio', sa.Integer(), nullable=True),
    sa.Column('ultimo_mes', sa.Integer(), nullable=True),
    sa.Column('ultimo_anio', sa.Integer(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('nit')
    )
    op.create_index(op.f('ix_empresa_aliada_nit9'), 'empresa_aliada', ['nit9'], unique=True)
    op.create_table('periodo_base_ssff',
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('mes_nombre', sa.String(length=20), nullable=True),
    sa.Column('archivo', sa.String(length=255), nullable=True),
    sa.Column('ruta', sa.String(length=500), nullable=True),
    sa.Column('fecha_proceso', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('empresas_encontradas', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('anio', 'mes', name='pk_periodo_base_ssff')
    )
    op.create_table('reporte_rechazo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nit', sa.String(length=15), nullable=True),
    sa.Column('nit9', sa.CHAR(length=9), nullable=True),
    sa.Column('aliado', sa.String(length=200), nullable=True),
    sa.Column('anio', sa.Integer(), nullable=True),
    sa.Column('mes', sa.Integer(), nullable=True),
    sa.Column('fecha_rechazo', sa.DateTime(), nullable=True),
    sa.Column('destinatario', sa.String(length=200), nullable=True),
    sa.Column('asunto', sa.String(length=255), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('intento', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reporte_rechazo_nit9'), 'reporte_rechazo', ['nit9'], unique=False)
    op.create_table('usuario',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('ADMIN', 'VIEWER', name='rol_usuario'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('primer_login', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('colaborador',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cedula', sa.String(length=15), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=True),
    sa.Column('apellidos', sa.String(length=100), nullable=True),
    sa.Column('nit_empresa', sa.CHAR(length=9), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('nombre_empresa_legible', sa.String(length=200), nullable=True),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('existe_planilla', sa.Enum('SI', 'NO', 'NA', name='cobertura_flag'), nullable=True),
    sa.Column('novedad_retiro', sa.Enum('SI', 'NO', 'NA', name='cobertura_flag'), nullable=True),
    sa.Column('existe_nomina', sa.Enum('SI', 'NO', 'NA', name='cobertura_flag'), nullable=True),
    sa.ForeignKeyConstraint(['nit_empresa'], ['empresa_aliada.nit9'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula', 'anio', 'mes', name='uq_colaborador_periodo')
    )
    op.create_index(op.f('ix_colaborador_cedula'), 'colaborador', ['cedula'], unique=False)
    op.create_index(op.f('ix_colaborador_nit_empresa'), 'colaborador', ['nit_empresa'], unique=False)
    op.create_table('reporte_nomina',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('nit', sa.String(length=15), nullable=False),
    sa.Column('nit9', sa.CHAR(length=9), nullable=False),
    sa.Column('aliado', sa.String(length=200), nullable=True),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes_obligacion', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('VALIDADO_OK', 'RECHAZADO', 'VALIDADO_INDIVIDUAL', name='estado_reporte'), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=True),
    sa.Column('tipo_planilla', sa.String(length=100), nullable=True),
    sa.Column('cantidad_validos', sa.Integer(), nullable=True),
    sa.Column('rechazo', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['nit9'], ['empresa_aliada.nit9'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reporte_nomina_nit9'), 'reporte_nomina', ['nit9'], unique=False)
    op.create_table('reporte_ss',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('nit', sa.String(length=15), nullable=False),
    sa.Column('nit9', sa.CHAR(length=9), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes_obligacion', sa.Integer(), nullable=False),
    sa.Column('operador', sa.String(length=100), nullable=True),
    sa.Column('aliado', sa.String(length=200), nullable=True),
    sa.Column('quien_envia', sa.String(length=200), nullable=True),
    sa.Column('tipo_planilla', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.Enum('VALIDADO_OK', 'RECHAZADO', 'VALIDADO_INDIVIDUAL', name='estado_reporte'), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=True),
    sa.Column('fecha_recepcion', sa.DateTime(), nullable=True),
    sa.Column('cantidad_validos', sa.Integer(), nullable=True),
    sa.Column('rechazo', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['nit9'], ['empresa_aliada.nit9'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reporte_ss_nit9'), 'reporte_ss', ['nit9'], unique=False)
    op.create_table('seguimiento_mensual',
    sa.Column('nit9', sa.CHAR(length=9), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('mes_nombre', sa.String(length=20), nullable=True),
    sa.Column('nombre_empresa', sa.String(length=200), nullable=True),
    sa.Column('ss_fecha_plazo', sa.Date(), nullable=True),
    sa.Column('ss_fecha_pago', sa.Date(), nullable=True),
    sa.Column('ss_estado', sa.Enum('CUMPLE', 'EN_MORA', 'PENDIENTE', name='estado_seguimiento'), nullable=True),
    sa.Column('ss_dias_mora', sa.Integer(), nullable=True),
    sa.Column('ss_fecha_verif', sa.Date(), nullable=True),
    sa.Column('nomina_estado', sa.Enum('CUMPLE', 'EN_MORA', 'PENDIENTE', name='estado_seguimiento'), nullable=True),
    sa.Column('nomina_fecha_plazo', sa.Date(), nullable=True),
    sa.Column('nomina_fecha_pago', sa.Date(), nullable=True),
    sa.Column('nomina_dias_mora', sa.Integer(), nullable=True),
    sa.Column('nomina_fecha_verif', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['nit9'], ['empresa_aliada.nit9'], ),
    sa.PrimaryKeyConstraint('nit9', 'anio', 'mes', name='pk_seguimiento_mensual')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seguimiento_mensual')
    op.drop_index(op.f('ix_reporte_ss_nit9'), table_name='reporte_ss')
    op.drop_table('reporte_ss')
    op.drop_index(op.f('ix_reporte_nomina_nit9'), table_name='reporte_nomina')
    op.drop_table('reporte_nomina')
    op.drop_index(op.f('ix_colaborador_nit_empresa'), table_name='colaborador')
    op.drop_index(op.f('ix_colaborador_cedula'), table_name='colaborador')
    op.drop_table('colaborador')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_reporte_rechazo_nit9'), table_name='reporte_rechazo')
    op.drop_table('reporte_rechazo')
    op.drop_table('periodo_base_ssff')
    op.drop_index(op.f('ix_empresa_aliada_nit9'), table_name='empresa_aliada')
    op.drop_table('empresa_aliada')
    # ### end Alembic commands ###
